### ISSUE TITLE
Just thoughts...

### ISSUE THREAD

**Issue by ansel1** [ExpansiveWorlds/instrumentedsql#5]
I just did something like this myself last night.  Couple thoughts about your approach:

1. I chose to wrap the driver.Conn, rather than the driver.Driver, to deal with pq not exporting it's driver impl.
2. I was nervous about implementing all the optional driver interfaces in my wrapper, and taking on the responsibility of adapting to drivers which didn't implement all of them.  Seems like golang's own sql package may add improvements or bug fixes to their adaptation code that you'll need to keep up with.  But the only alternative I can see is implementing a bunch of structs which implement *every* possible combination of the optional interfaces.
3. I started to add more stuff to my wrapper (like metrics, logging, tracing, etc), and came to the same conclusion you did: it would be more flexible to have the wrapper call hooks.  Which made me think of httptrace.

**Comment by luna-duclos** [comment]
for pq, I put in a PR with them: lib/pq#585

Indeed, while the code copied from stdlib is minimal, there is indeed some, I see little alternative but keeping up with changes .. it's only really maybe 20-30 lines of code, so I'm comfortable with that

tracing/logging fit quite well with the paradigm I picked, the main reason I'd like a custom hook is for people to hook in metrics, seeing as not everyone will want the same metrics, a hook would be ideal for it.

**Comment by luna-duclos** [comment]
I'd be curious to see your code, is there anything you'd like to merge into this codebase you're doing differently perhaps ?

**Comment by ansel1** [comment]
No, I've got nothing interesting yet.  My code is essentially the same as yours, but only works with pq (because I only chose to implement and forward the interfaces I *know* pq implements).  Your stuff is definitely just mine+better.  But I think I'm going to take a crack are rewriting it following the httptrace pattern of just hooks, which can be composed.  Then you can layer in logging, tracing, metrics, etc.

**Comment by luna-duclos** [comment]
*Nods* Sounds cool! Good luck
